[build]
  publish = ".presite"
  command = "npx pnpm i && npx pnpm run build && npx pnpm run prerender"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-chromium"
