[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile=false && npm run build && npm run prerender"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-chromium"
