name: Build and Deploy "Daily Good Deeds"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.9.3
          run_install: |
            - recursive: true
      
      - run: pnpm build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: dist # The folder the action should deploy.
